### PR TITLE
Notebook doc builder issue resolved + hatched mask plotting feature added

### PR DESCRIPTION
**Pull request by isilber**

### CODE REVIEW

**Comment by isilber** [comment]
Still without a solution. Thought it could be italics, the new version of [nbsphinx](https://github.com/spatialaudio/nbsphinx/issues/310), having the title in the same markdown cell as regular text, lack of tags, or lack of title in the metadata, but no help.

**Comment by isilber** [comment]
Just encountered the same documentation errors when tried to update a different repository so I presume that this is something more related to one of the very latest updates of sphinx(?)? Other ideas?

**Comment by isilber** [comment]
I finally managed to resolve this issue!
Apparently, it is not related to nbconvert, nbimporter, or nbformat (BTW, Notebooks currently support nbformat versions not higher than 4.4), but in Jinja2, which is not well integrated with sphinx. An official release of version 3.0 during April has caused all the issues, so in order to resolve it, I needed to specify a Jinja2 version < 3.0.

Because I also added some plotting features included in our manuscript (as well as other minor fixes since the last release from March), I recommend releasing a new version (wonder whether this justifies 1.1.0 or just 1.0.1).

**Comment by rcjackson** [comment]
I will make a 1.1.0 release out of this. All checks have passed, so I am merging.

**Pull request merged**
