### PR TITLE
Instrument sub-classes and scattering LUT updates

### PR DESCRIPTION
**Pull request by isilber**

### CODE REVIEW

**Comment by rcjackson** [comment]
I think there is something in your notebook that is not supported by sphinx. I saw a couple of checkboxes in it that might be causing it to stop. However, I've so far put a setting in there to ignore errors in the notebooks when building the docs. It should still appear correctly on the website, If not, I would suggest removing the output from the cell with the checkboxes in it.

**Comment by rcjackson** [comment]
I noticed that your notebook uses nbformat 4.0. I think you need to upgrade your nbformat on your PC to 5.1. I suspect there is a conflict here with the version sphinx is using and the one you have on your pc.

**Comment by isilber** [comment]
That is interesting because I do use 5.1.2. Don't know why the notebook version was set to 4.

**Comment by rcjackson** [comment]
Good catch on the typo. It was causing the pep8 checker to fail and I was wondering why.

**Comment by isilber** [comment]
Don't know if related, but the demo notebook is no longer seen in the documentation.

**Comment by rcjackson** [comment]
/home/travis/build/columncolab/EMC2/doc/source/index.rst:32: WARNING: toctree contains reference to document 'EMC2example' that doesn't have a title: no link will be generated
Sphinx seems to be complaining about there being no title on the example notebook.

Bobby

**Comment by isilber** [comment]
That's weird. I have nbformat v. 5.1.2 but I cannot load the notebook with the current settings unless I change the nbformat version in the notebook back to  4.4.
I note that previously the nbformat version did not make any issues in building the docs (still working fine when built locally).

**Pull request merged**
